/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.logging.Logger;

import javax.swing.JOptionPane;
/**
 *
 * @author omarm
 */
public class RequestRefill extends javax.swing.JFrame {
    
    private static final Logger logger = Logger.getLogger(RequestRefill.class.getName());
    private String doctorName;
    private String doctorEmail;

    /**
     * Creates new form java
     */
    public RequestRefill() {
        initComponents();
        setLocationRelativeTo(null); // Center the window
        setTitle("Request Medicine Refill");
    }
    
    /**
     * Creates new form with doctor information
     */
    public RequestRefill(String doctorName, String doctorEmail) {
        this.doctorName = doctorName;
        this.doctorEmail = doctorEmail;
        initComponents();
        setLocationRelativeTo(null); // Center the window
        setTitle("Request Medicine Refill");
    }
    
    public String getDoctorName() {
        return doctorName;
    }
    
    public String getDoctorEmail() {
        return doctorEmail;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSendRequest = new javax.swing.JButton();
        cmbPharmacist = new javax.swing.JComboBox<>();
        cmbMedicine = new javax.swing.JComboBox<>();
        txtQuantity = new javax.swing.JTextField();
        lblPharmacist = new javax.swing.JLabel();
        lblMedicine = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Request Medicine Refill");

        btnSendRequest.setText("Send Request");
        btnSendRequest.addActionListener(this::btnSendRequestActionPerformed);

        cmbPharmacist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loading..." }));
        cmbPharmacist.setToolTipText("Select a pharmacist");

        cmbMedicine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loading..." }));
        cmbMedicine.setToolTipText("Select a medicine");

        txtQuantity.setToolTipText("Enter refill quantity");

        lblPharmacist.setText("Pharmacist:");

        lblMedicine.setText("Medicine:");

        lblQuantity.setText("Quantity:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPharmacist)
                    .addComponent(lblMedicine)
                    .addComponent(lblQuantity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbPharmacist, 0, 250, Short.MAX_VALUE)
                    .addComponent(cmbMedicine, 0, 250, Short.MAX_VALUE)
                    .addComponent(txtQuantity)
                    .addComponent(btnSendRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPharmacist)
                    .addComponent(cmbPharmacist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicine)
                    .addComponent(cmbMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnSendRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JComboBox<String> getCmbPharmacist() {
        return cmbPharmacist;
    }

    public javax.swing.JComboBox<String> getCmbMedicine() {
        return cmbMedicine;
    }

    public javax.swing.JTextField getTxtQuantity() {
        return txtQuantity;
    }

    public javax.swing.JButton getBtnSendRequest() {
        return btnSendRequest;
    }

    public void setOutputMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new RequestRefill().setVisible(true));
    }
   
    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendRequestActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JComboBox<String> cmbPharmacist;
    private javax.swing.JComboBox<String> cmbMedicine;
    private javax.swing.JLabel lblMedicine;
    private javax.swing.JLabel lblPharmacist;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}