/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JRadioButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author salma
 */
public class ViewProfile extends javax.swing.JFrame {

    /**
     * Creates new form ViewProfile
     */
    private String patientEmail;
    
    public ViewProfile() {
        initComponents();
        this.setVisible(true);
    }
    
    public ViewProfile(String patientEmail) {
        this.patientEmail = patientEmail;
        initComponents();
        this.setVisible(true);
    }
    
    public String getPatientEmail() {
        return patientEmail;
    }
    
    // Getters for GUI components
    public JTextField getNameField() {
        return jTextField1;
    }
    
    public JTextField getDateOfBirthField() {
        return jTextField2;
    }
    
    public String getGender() {
        if (rdbMale.isSelected()) return "Male";
        if (rdbFemale.isSelected()) return "Female";
        return null;
    }
    
    public void setGender(String gender) {
        if (gender != null) {
            if (gender.equalsIgnoreCase("Male")) {
                rdbMale.setSelected(true);
            } else if (gender.equalsIgnoreCase("Female")) {
                rdbFemale.setSelected(true);
            }
        }
    }
    
    public JTextField getAddressField() {
        return jTextField4;
    }
    
    public JTextField getPhoneNumberField() {
        return jTextField5;
    }
    
    public JButton getEditButton() {
        return jButton1;
    }
    
    // Validation methods
    public boolean validateForm() {
        // Validate name
        if (jTextField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name cannot be empty!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            jTextField1.requestFocus();
            return false;
        }
        
        // Validate date of birth
        if (jTextField2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Date of Birth cannot be empty!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            jTextField2.requestFocus();
            return false;
        }
        
        // Validate gender
        if (!rdbMale.isSelected() && !rdbFemale.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select a gender!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        // Validate address
        if (jTextField4.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address cannot be empty!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            jTextField4.requestFocus();
            return false;
        }
        
        // Validate phone number
        if (!validatePhoneNumber()) {
            JOptionPane.showMessageDialog(this, "Phone number must be a valid number!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            jTextField5.requestFocus();
            return false;
        }
        
        return true;
    }
    
    private boolean validatePhoneNumber() {
        String phoneNumber = jTextField5.getText().trim();
        if (phoneNumber.isEmpty()) {
            return false;
        }
        try {
            Long.parseLong(phoneNumber);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        rdbMale = new javax.swing.JRadioButton();
        rdbFemale = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name:");
        jLabel1.setForeground(new java.awt.Color(64, 64, 64));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12));

        jLabel2.setText("Date of Birth");
        jLabel2.setForeground(new java.awt.Color(64, 64, 64));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12));

        jLabel3.setText("Gender:");
        jLabel3.setForeground(new java.awt.Color(64, 64, 64));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12));

        jLabel4.setText("Address:");
        jLabel4.setForeground(new java.awt.Color(64, 64, 64));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12));

        jLabel5.setText("Phone Number:");
        jLabel5.setForeground(new java.awt.Color(64, 64, 64));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("View Profile");
        jLabel7.setBackground(new java.awt.Color(0, 0, 153));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setOpaque(true);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setEnabled(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 30));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 12));

        jTextField2.setEnabled(false);
        jTextField2.setPreferredSize(new java.awt.Dimension(200, 30));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 12));

        genderGroup.add(rdbMale);
        rdbMale.setText("Male");
        rdbMale.setEnabled(false);
        rdbMale.setBackground(new java.awt.Color(153, 204, 255));
        rdbMale.setOpaque(true);
        
        genderGroup.add(rdbFemale);
        rdbFemale.setText("Female");
        rdbFemale.setEnabled(false);
        rdbFemale.setBackground(new java.awt.Color(153, 204, 255));
        rdbFemale.setOpaque(true);

        jTextField4.setEnabled(false);
        jTextField4.setPreferredSize(new java.awt.Dimension(200, 30));
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 12));

        jTextField5.setEnabled(false);
        jTextField5.setPreferredSize(new java.awt.Dimension(200, 30));
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 12));
        
        // Add phone number validation
        jTextField5.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                validatePhoneNumberField();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                validatePhoneNumberField();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                validatePhoneNumberField();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, 30)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbMale)
                                .addGap(18, 18, 18)
                                .addComponent(rdbFemale))
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdbMale)
                    .addComponent(rdbFemale))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        pack();
        
        // Minimize the window size and center
        setSize(400, 450);
        setLocationRelativeTo(null);
        
        // Set background color for content pane (light blue)
        getContentPane().setBackground(new java.awt.Color(153, 204, 255));
        
        // Set button colors (dark blue background, white text)
        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Validate form before proceeding
        if (validateForm()) {
            // Form is valid, proceed with edit action
            // TODO add your handling code here:
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void validatePhoneNumberField() {
        String phoneNumber = jTextField5.getText().trim();
        if (!phoneNumber.isEmpty()) {
            try {
                Long.parseLong(phoneNumber);
                jTextField5.setForeground(new java.awt.Color(0, 0, 0));
            } catch (NumberFormatException e) {
                jTextField5.setForeground(new java.awt.Color(255, 0, 0));
            }
        } else {
            jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rdbFemale;
    private javax.swing.JRadioButton rdbMale;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
